/// Generic Dimensions
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_CARD_MEDIUM_2 = 12.0;
const MARGIN_MEDIUM_2 = 16.0;
const MARGIN_MEDIUM_3 = 20.0;
const MARGIN_LARGE = 24.0;
const MARGIN_XLARGE = 32.0;
const MARGIN_XXLARGE = 48.0;

const TEXT_HEADING_1X = 24.0;
const TEXT_HEADING_2X = 28.0;
const TEXT_BIG = 32.0;
const TEXT_REGULAR = 14.0;
const TEXT_REGULAR_2X = 16.0;
const TEXT_REGULAR_3X = 20.0;
const TEXT_SMALL = 10.0;
const TEXT_SMALL_2 = 12.0;

/// App Specific
const HOME_PAGE_AVATAR_SIZE = 56.0;
const HOME_PAGE_AVATAR_BORDER_WIDTH = 3.0;
const HOME_PAGE_SEARCH_BAR_HEIGHT = 52.0;
const HOME_PAGE_TOP_MARGIN = 60.0;
const APPOINTMENT_LIST_HEIGHT = 130.0;
const APPOINTMENT_LIST_ITEM_WIDTH = 250.0;
const TIMELINE_WIDTH = 14.0;
const LIST_ITEM_HEIGHT_IN_TIME_EVENT = 50.0;
const TIMELINE_DASH_WIDTH = 3.0;
const TIMELINE_DASH_HEIGHT = 10.0;
const EVENT_LIST_MARGIN = 25.0;
const DETAIL_PAGE_APPOINTMENT_LIST_TOP_MERGIN = 60.0;